[project]
name = "kva"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "pytest>=8.4.2",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
    "tqdm>=4.67.1",
]
